### ISSUE TITLE
I have it working but pygame window never updates

### ISSUE THREAD

**Issue by Robokan** [danijar/daydreamer#12]
Thanks for posting this. I have a Go1 and am doing active research with NN's and locomotion on it using motion capture. I would like to reproduce your work but things seem to just hang.

**in one window I have this:**

........

Encoder CNN shapes: {}
Encoder MLP shapes: {'vector': (16,)}
Decoder CNN shapes: {}
Decoder MLP shapes: {'vector': (16,)}
Synced last 0/0 trajectories.
Synced last 0/0 trajectories.
Logdir /home/bizon/logdir/run1
Initializing training replay...
Waiting for episodes.
Replay server listening on *:2222
Waiting for episodes.
Waiting for episodes.
Waiting for episodes.
Waiting for episodes.
Waiting for episodes.
Waiting for episodes.
Waiting for episodes.
Waiting for episodes.
Waiting for episodes.
Waiting for episodes.
Waiting for episodes.
Waiting for episodes.
Waiting for episodes.
Waiting for episodes.
Waiting for episodes.
Waiting for episodes.
Waiting for episodes.

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/bizon/anaconda3/envs/rldda1/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/bizon/anaconda3/envs/rldda1/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bizon/eric/daydreamer/embodied/replay/store.py", line 290, in _server
    self[key] = traj
  File "/home/bizon/eric/daydreamer/embodied/replay/store.py", line 272, in __setitem__
    self.store[key] = traj
  File "/home/bizon/eric/daydreamer/embodied/replay/store.py", line 231, in __setitem__
    self.store[key] = traj
  File "/home/bizon/eric/daydreamer/embodied/replay/store.py", line 188, in __setitem__
    self.disk_store[key] = traj
  File "/home/bizon/eric/daydreamer/embodied/replay/store.py", line 98, in __setitem__
    filename = self._format(key, traj)
  File "/home/bizon/eric/daydreamer/embodied/replay/store.py", line 144, in _format
    reward = str(int(traj['reward'].sum())).replace('-', 'm')
ValueError: cannot convert float NaN to integer
Initializing agent...
Tracing train function.
Found 6727954 model parameters.

.......

Tracing train function.
Initialization done.
Existing checkpoint not found.
Saving checkpoint: /home/bizon/logdir/run1/agent.pkl
Saving module with 341 tensors and 30344083 parameters.
Existing checkpoint not found.
Saving checkpoint: /home/bizon/logdir/run1/learner.pkl
Waiting for train data prefill (0/5000.0)...
Waiting for train data prefill (0/5000.0)...
Waiting for train data prefill (0/5000.0)...
Waiting for train data prefill (0/5000.0)...
Waiting for train data prefill (0/5000.0)...
Waiting for train data prefill (0/5000.0)...
Waiting for train data prefill (0/5000.0)...
Waiting for train data prefill (0/5000.0)...
Waiting for train data prefill (0/5000.0)...
Waiting for train data prefill (0/5000.0)...
Waiting for train data prefill (0/5000.0)...
Waiting for train data prefill (0/5000.0)...
Waiting for train data prefill (0/5000.0)...

**in the other I have this:**

......

/home/bizon/eric/daydreamer/motion_imitation/robots/a1.py:190: RuntimeWarning: invalid value encountered in arccos
  theta_knee = -np.arccos(
argv[0]=
UDP Initialized. Port: 8080 
Stand up reset called! -1 None
Stand up reset called! -1 None
Stand up reset called! 0.0 None
Encoder CNN shapes: {}
Encoder MLP shapes: {'vector': (16,)}
Decoder CNN shapes: {}
Decoder MLP shapes: {'vector': (16,)}
Using remote store via ZMQ on localhost:2222
Waiting for response from localhost:2222...
Connection to localhost:2222 successful!
Logdir: /home/bizon/logdir/run1
Existing checkpoint not found.
Saving checkpoint: /home/bizon/logdir/run1/worker0/actor.pkl
Fill dataset (5000.0 steps, 1 episode).
Stand up reset called! -1 None
Stand up reset called! 0.0 None
Episode has 250 steps and return nan.
[12550] episode/length 250 / episode/score nan / episode/average_reward nan / episode/reward_rate 0 / replay/replay_episodes 1 / replay/replay_ep_length 251 / replay/replay_ep_return nan

**And the pygame window is saying "train.py" is not responding. Any ideas? What version of pygame are you using?**

**Comment by danijar** [comment]
From reading the error message, it seems like your environment is returning NaN as a reward?

**Comment by Robokan** [comment]
I am just running the 2 commands 

CUDA_VISIBLE_DEVICES=0 python embodied/agents/dreamerv2plus/train.py --configs a1 --task a1_sim --run learning --tf.platform gpu --logdir ~/logdir/run1

and

CUDA_VISIBLE_DEVICES=1 python embodied/agents/dreamerv2plus/train.py --configs a1 --task a1_real --run acting --tf.platform gpu --env.kbreset True --imag_horizon 1 --replay_chunk 8 --replay_fixed.minlen 32 --imag_horizon 1 --logdir ~/logdir/run1


Maybe it's a library incompatibility problem. Here is how I set it up:

sudo apt install ffmpeg
pip install tensorflow-gpu==2.6.0 tensorflow_probability==0.12.2 ruamel.yaml

conda install -c conda-forge cudatoolkit=11.8.0

sudo apt install liblcm-bin
pip install dm-sonnet graphs install gym==0.22.0 attrs pybullet filterpy pygame cloudpickle

I then added ~/daydreamer/third_party/unitree_legged_sdk/bin to the LD_LIBRARY_PATH

What versions of these libraries are you running?

**Comment by Robokan** [comment]
I was hoping to get this running so I can optimize the controller I already have running on the go1. He is my work:

https://www.youtube.com/playlist?list=PLRomMJJB2S8ZIspr5rFre0uzoUa4taO42

**Comment by RainsClear3** [comment]
@Robokan Have you solved this problem?I got the same problem too.Hope you can give me some advice,Thank you!

**Comment by Robokan** [comment]
I was never able to get to work. Anyone else make any progress?

**Comment by RainsClear3** [comment]
@Robokan You can replace the another task to a1_sim, then you can get it!

**Comment by Robokan** [comment]
I tried replacing a1_real with a1_sim and things work. From the code it looks like the pygame window just lets you pause or continue training. What I was hoping was it was possible to see the robot learning to get up. How to know if it is even working without that ability?

**Comment by RainsClear3** [comment]
Did your pybullet window run? pygame window is gray，press c or p to continue or pause the training thread.



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 14, 2024 07:26 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [danijar/daydreamer] I have it working but pygame window neverupdates (Issue #12)




 
I tried replacing a1_real with a1_sim but I still have a blank pygame window during training. Is this happening for you? Shouldn't I be able to see what's happening in the window?

**Comment by Robokan** [comment]
Yes I got the pygame window working. I didn't realize it was merely for pausing the thread at first. Now the real question is how to see what's actually happening here in the sim. I have the Go1 EDU so I might take a try at porting the A1 code to Go1. Or just see if I can get daydreamer v3 working for the Go1. I also built my own Go1 simulator in Isaac Sim so one option is to just get it running on my simulator first. I would like to reproduce Danijar's work. Just trying to figure out the best avenue.

**Comment by Robokan** [comment]
Closing this as I was able to finally get it working.

**Comment by Robokan** [comment]
One you got everything setup you can visualize the learning process of the A1 robot by going to line 13 in enbodies/envs/a1/a1.py and setting         
enable_rendering=True

when you execute the commands in each window make sure they both have 'sim' and not 'real' as the target. Then 2 windows show up one for each instead of the pygame window.

**Comment by TREEee14ee** [comment]
@Robokan Hello! The information you gave is very useful for me, I have now successfully run A1 robot and Go1 robot in simulation, and I would like to run Danijar's work on my Go1 as well, have you successfully run it on your Go1?

**Comment by Robokan** [comment]
Unfortunately I just broke one of the motors on my go1. Looks to be a short somewhere so I haven't tried to get it working. Let me know if you make any progress!
