### ISSUE TITLE
Using with custom gym wrapper 

### ISSUE THREAD

**Issue by azizbelkhiria** [danijar/daydreamer#3]
How can we use this with a custom gym wrapper like in api.py from dreamv2?

**Comment by danijar** [comment]
Hi, you can create your end, wrap it as needed, and then pass it to embodied.envs.Gym() to convert it to the API the agent understands.

**Comment by azizbelkhiria** [comment]
Could you please specify how this is done? Do we need to modify the config file and what is the terminal command to start training in this case?
