### ISSUE TITLE
setup.py is required.

### ISSUE THREAD

**Issue by ZJEast** [danijar/daydreamer#7]
I want to try this paper's method but I got lots of problems about dependency, such as gym==0.18.0, sonnet, boost/ptr.h and so on.

**Comment by Robokan** [comment]
I got the libraries basically working by first installing the requirements for dreamerv2:
sudo apt  install ffmpeg
pip install tensorflow-gpu==2.6.0 tensorflow_probability==0.12.2 ruamel.yaml 

if your cuda version is 12 it won't work so install 11.8 toolkit. I am using conda so I did it like this:
conda install -c conda-forge cudatoolkit=11.8.0

Next I install these:

sudo apt install liblcm-bin
pip install dm-sonnet graphs install gym==0.22.0 attrs pybullet filterpy pygame cloudpickle

I then added  ~/daydreamer/third_party/unitree_legged_sdk/bin to the LD_LIBRARY_PATH

It works but the pygame window is blank. If anyone gets this fully working please post!

**Comment by TREEee14ee** [comment]
@Robokan I tried following your steps and now I'm experiencing the same problem as you, did you solve the problem?

**Comment by Robokan** [comment]
This is as far as I got. I keep meaning to come back to it.

**Comment by Robokan** [comment]
Turns out the pygame window is supposed to be blank. It is only meant as a way to pause and continue the thread. 'p' will pause turning the window red and 'c' will continue turning the window gray. 'r' resets it I believe. Does this work for you?

**Comment by Robokan** [comment]
One you got everything setup you can visualize the learning process of the A1 robot by going to line 13 in enbodies/envs/a1/a1.py and setting         
enable_rendering=True

when you execute the commands in each window make sure they both have 'sim' and not 'real' as the target. Then 2 windows show up one for each.
