### ISSUE TITLE
Train ratio on physical robots

### ISSUE THREAD

**Issue by pplntech** [danijar/daydreamer#8]
Hi Danijar, first of all, thank you so much for making the code publicly available! Let me ask a question regarding train ratio on physical robots.

In previous Dreamer implementation for sim, I see a mechanism to control `train ratio` to data collection, e.g. with `config.train_every` in V1 and V2 and `config.run.train_ratio` in V3. Also, Fig. 6 (a) from Dreamer V3 paper (also shown below left) shows that different train ratio leads to distinct sample efficiency although each configuration shown in the figure ended up with success, which means that the algorithm is pretty robust to training ratio. Still, I think we may want to do hyperparameter search over train ratio to find an optimal number for an environment which is also evidenced by varying train ratio used for different environment in Table A.1 from Dreamer V3 (also shown below right).

<img src="https://github.com/danijar/daydreamer/assets/8488324/3b20530a-50fd-4c31-a07d-7761042e73ea" height="240">
<img src="https://github.com/danijar/daydreamer/assets/8488324/74ff028a-ed29-4559-9016-16e1f5a3916a" height="240">

On the other hand, to the best of my knowledge, the mechanism of `train_ratio` control is absent in this repository (and also [DreamerV3 based experiment](https://github.com/danijar/daydreamer/issues/6#issuecomment-1448239702) where --run.train_ratio is set to -1). Considering learning process is faster than acting process in real robots, I assume train ratio would be high although I don't have an exact measurement nor a control to adjust train ratio for now. Referring to Fig. 6 (a), higher train ratio tends to have higher sample efficiency, but uncontrollably and unexpectedly high train ratio might result in performance degradation. For example, world models might overfit to the current replay buffer, which in turn would damage the overall performance.

I wonder you had similar kinds of concerns w.r.t. train ratio on training physical robots. And how do you think about exploring different train ratio on physical robots?

Thanks. :)

**Comment by danijar** [comment]
Hi, DayDreamer runs acting and learning in separate processes and at maximum speed, so there is no rate limiting.
